# Import packages
```{r message=FALSE}
library(ProjectTemplate); load.project()
set.seed(1234)
settings <- analysis_settings("quick")
source('jags//jags_subtasks-2.r')
jagsdata <- get_data_subtasks()
```


```{r}
# s: subtasks
# p or e: power versus exponential
# tu tc: theta2 unconstrained / constrained
# gu gc: gamma unconstrained / constrained
# st sf: strategies true/ strategies false

model_grid <-  expand.grid(f=c('power3', 'exp3'), theta2_constraint=c(TRUE, FALSE),  
                           gamma_constraint=c(TRUE, FALSE), strategy_predictors=c(TRUE, FALSE),
                           stringsAsFactors=FALSE)
model_grid$name <- paste(
    sapply(model_grid$f, switch, power3='p3', exp3='e3'),
    ifelse(model_grid$theta2_constraint, 'tc', 'tu'),
    ifelse(model_grid$gamma_constraint, 'gc', 'gu'),
    ifelse(model_grid$strategy_predictors, 'st', 'sf'), 
    sep="_")

model_fits <- list()
for (i in seq(nrow(model_grid))) {
    cat(i)
    script <- jags_subtasks_gamma(f=model_grid$f[i], theta2_constraint=model_grid$theta2_constraint[i], 
                            gamma_constraint=model_grid$gamma_constraint[i], strategy_predictors=model_grid$strategy_predictors[i])
    model_fits[[ model_grid$name[i] ]] <- run_jags(script$script, jagsdata,  script$parameters, dic.run=TRUE)
}


# dic
dics <-sapply(model_fits, function(X) get_dic(X$dic))
model_grid <- cbind(model_grid,  t(dics))
model_grid$result <-  with(model_grid, paste0(round(penalised_deviance, 0), " (",round(penalty, 0), ", ", round(deviance, 0), ")"))
model_grid$order <- order(model_grid$strategy_predictors, model_grid$f, model_grid$gamma_constraint, model_grid$theta2_constraint)
subtask_dic <- model_grid[model_grid$order, c('name', 'strategy_predictors', 'result')] 
subtask_dic <- cbind(subtask_dic[ subtask_dic$strategy_predictors == FALSE, c('name', 'result')], 
                    subtask_dic[ subtask_dic$strategy_predictors == TRUE, c('result')])
names(subtask_dic) <- c('model', 'no_strategy', 'strategy')

write.csv(model_grid, 'graphs/overall_subtasks_dics.csv', na="")
write.csv(subtask_dic, 'graphs/summary_subtasks_dics.csv', na="")

# test particular model
# script <- jags_subtasks(f='power3', theta2_constraint=FALSE, gamma_constraint=FALSE,strategy_predictors=FALSE)
# model_fits$s <-run_jags(script$script, jagsdata,  script$parameters, dic.run=TRUE)

# # examine subtask correlations
# script <- jags_subtasks(f='power3', theta2_constraint=FALSE,gamma_constraint=FALSE, strategy_predictors=FALSE)
# subcor <- run_jags(script$script, jagsdata,  c('theta1_1', 'theta2_1', 'theta3_1'), dic.run=FALSE)
# subcor$samples
# 
# grep('theta', script$parameters, value=TRUE)
# cat(script$script)


# s3b DIC worse by about 100
# model_fits$s3$dic
# model_fits$s3e$dic
# model_fits$s3b$dic
# model_fits$s3b2$dic
# 
# # s3c DIC worse by about 500
# model_fits$s3b$dic
# model_fits$s3c$dic


# p3_tu_gu_su
# p3_tc_gc_su
# main table
subtasks_ptable <- create_parameter_table(
    samples = list(
        e3_tu_gu_sf=model_fits$e3_tu_gu_sf$samples, 
        p3_tu_gu_sf=model_fits$p3_tu_gu_sf$samples, 
                   p3_tc_gc_sf=model_fits$p3_tc_gc_sf$samples),
        dics = list(
            e3_tu_gu_sf=model_fits$e3_tu_gu_sf$dic, 
            p3_tu_gu_sf=model_fits$p3_tu_gu_sf$dic, 
            p3_tc_gc_sf=model_fits$p3_tc_gc_sf$dic),
            parameter_order =  c(          
                "theta1_1.mu", "theta1_2.mu", "theta1_3.mu",
          "theta2_1.mu", "theta2_2.mu", "theta2_3.mu",
          "theta3_1.mu", "theta3_2.mu", "theta3_3.mu",
          "gamma.mu", "theta2.mu","sigma.mu",  
          "theta1_1.sigma", "theta1_2.sigma", "theta1_3.sigma",
          "theta2_1.sigma", "theta2_2.sigma", "theta2_3.sigma",
          "theta3_1.sigma", "theta3_2.sigma", "theta3_3.sigma",
          "gamma.sigma", "theta2.sigma","sigma.sigma"))

write.csv(subtasks_ptable, 'graphs/subtasks_parameter_table.csv', na="")


# strategy ptable
# in both cases the constraints lead to worse fits
lambdas <- expand.grid(a=1:6, b=1:3)
lambdas <- lambdas[order(lambdas$a, lambdas$b), ]
lambdas <- paste0('lambda[',lambdas$a, ',', lambdas$b, ']')
components_ptable <- create_parameter_table(
    samples = list(p3_tu_gu_st=model_fits$p3_tu_gu_st$samples, 
                   p3_tc_gc_st=model_fits$p3_tc_gc_st$samples),
        dics = list(p3_tu_gu_st=model_fits$p3_tu_gu_st$dic, 
                    p3_tc_gc_st=model_fits$p3_tc_gc_st$dic),
            parameter_order =  c(          
                "theta1_1.mu", "theta1_2.mu", "theta1_3.mu",
          "theta2_1.mu", "theta2_2.mu", "theta2_3.mu",
          "theta3_1.mu", "theta3_2.mu", "theta3_3.mu",
          "gamma.mu", "theta2.mu","sigma.mu",  
          "theta1_1.sigma", "theta1_2.sigma", "theta1_3.sigma",
          "theta2_1.sigma", "theta2_2.sigma", "theta2_3.sigma",
          "theta3_1.sigma", "theta3_2.sigma", "theta3_3.sigma",
          "gamma.sigma", "theta2.sigma","sigma.sigma",
                lambdas))

write.csv(components_ptable, 'graphs/components_parameter_table.csv', na="")

lambda_summary_function <- function() {
    x <- summary(model_fits$p3_tu_gu_st$samples)
    matches <- grep("lambda", row.names(x$statistics))
    x_mean <- x$statistics[matches,'Mean']
    x_ci <- x$quantiles[matches,c("2.5%", "97.5%")]
    x_table <- data.frame(Mean=x_mean, x_ci)
    names(x_table) <- c("Mean", "CI_2.5", "CI_97.5")
    exp_x_table <- exp(x_table)

    exp_x_table$text <- paste0(specify_decimal(exp_x_table[,'Mean'], 2), " (", 
                                   specify_decimal(exp_x_table[, 'CI_2.5'],2), ", ", 
                                   specify_decimal(exp_x_table[,'CI_97.5'], 2), ")")
    
                         
    exp_x_summary <- cbind(IG=exp_x_table[1:6, 'text'], 
          F=exp_x_table[7:12, 'text'], 
          TT=exp_x_table[13:18, 'text'])
    row.names(exp_x_summary) <- paste0('lambda', 1:6)
    list(x_table=x_table, exp_x_table=exp_x_table, exp_x_summary=exp_x_summary)
}

lambda_summary <- lambda_summary_function()
    
write.csv(lambda_summary$x_table, 'graphs/lambda_summary_x_table.csv')
write.csv(lambda_summary$exp_x_table, 'graphs/lambda_summary_exp_x_table.csv')
write.csv(lambda_summary$exp_x_summary, 'graphs/lambda_summary_exp_x_summary.csv')


# old code update with new names
# plot(density(model_fits$s3$dic$penalty))
# plot(density(model_fits$s3$dic$deviance))
# round(sum(model_fits$s3$dic$deviance))
# plot(density(exp(-model_fits$s3$dic$deviance/2)))
# model_fits$s3$dic
save.image()
# load('.RData')
```

# updated subtasks
```{r}
# source('jags/jags_subtasks-2.r')
# models <- list()
# jags_model <- jags_subtasks_gamma(f='power3', strategy_predictors=FALSE)
# line_num_cat(jags_subtasks_gamma()$script)
# # write(jags_model, 'jags/archive/strategy-test-1.r')
# models$mod1 <- run_jags(jags_model$script, jagsdata,  jags_model$parameters, dic.run=TRUE)
# models$mod1$dic
# # line_num_cat(jags_subtasks(strategy_predictors=TRUE)$script)
```

# Model Recovery Simulation (Exp versus Power - subtasks)

```{r model_recovery_pve}
source('jags/jags_subtasks-2.r')
settings <- analysis_settings(analysis='standard')
settings$n.chains <- 2
x <- model_recovery_subtaskspve(20)

# 
results <-  x$design
results$meandeviance <-  sapply(x$fits, function(X) sum(X$dic$deviance))
results$penalty <-  sapply(x$fits, function(X) sum(X$dic$penalty))
results$dic <- results$meandeviance + results$penalty
results$devianceatmean <- results$meandeviance - results$penalty
results

# results <- read.csv('graphs/model_recovery_simulation_pve.csv', row.names=1)
sresults <- split(results, results$estimator)
fresults <- sresults$exp[, c('k', 'generator', 'datasets_id')]
fpower <- sresults$power[, c('datasets_id', 'dic')]
fexp <- sresults$exp[, c('datasets_id', 'dic')]
names(fpower) <- c('datasets_id', 'dic_power')
names(fexp) <- c('datasets_id', 'dic_exp')
fresults <- merge(fresults, fpower)
fresults <- merge(fresults, fexp)
fresults$dicdiff <- fresults$dic_power - fresults$dic_exp

summarise_dic_diff <- function(x) {
    list(
        prop_better=mean(x > 0),
        mean_dic_improvement=mean(x),
        sd_dic_improvement=sd(x),
        min_dic_improvement=min(x),
        max_dic_improvement=max(x),
        N = length(x)
    )
}

pve_dic_diff <- list()
pve_dic_diff$exp <- summarise_dic_diff(fresults[fresults$generator=='exp', 'dicdiff'])
pve_dic_diff$power <- summarise_dic_diff(-fresults[fresults$generator=='power', 'dicdiff'])

write.csv(fresults, file='graphs/model_recovery_pve.csv')
sink('graphs/model_recovery_pve.csv', append=TRUE)
date()
pve_dic_diff
settings
sink()


# boxplot(dicdiff ~ generator, fresults, ylim=c(-600, 600), ylab="DIC Power - DIC Exp (Pos means Exp is better)", 
#         xlab="Data Generating Process")
# abline(h=0)
```

# Model Recovery: Constrained/Unconstrained and Strategies (With and Without)
```{r model_recovery_cus}
settings <- analysis_settings(analysis='standard')
settings$n.chains <- 2
source('jags/jags_subtasks-2.r')
x <- model_recovery_subtaskscus(20)

results <-  x$design
results$meandeviance <-  sapply(x$fits, function(X) sum(X$dic$deviance))
results$penalty <-  sapply(x$fits, function(X) sum(X$dic$penalty))
results$dic <- results$meandeviance + results$penalty
results$devianceatmean <- results$meandeviance - results$penalty
results

# results <- read.csv('graphs/model_recovery_simulation_pve.csv', row.names=1)
results$estimtator_name <- paste0(ifelse(results$constraints, 'constrained', 'unconstrained'), "_", 
                                  ifelse(results$strategies, 'withstrategies', 'withoutstrategies'))
sresults <- split(results, results$estimtator_name)

fresults <- sresults$constrained_withoutstrategies[, c('k', 'generator', 'datasets_id')]
fdic <- lapply(sresults, function(X) X[, c('datasets_id', 'dic')])
for (i in seq(fdic)) {
    names(fdic[[i]]) <-  c('datasets_id', paste0("dic_", names(fdic)[i]))
    fresults <- merge(fresults, fdic[[i]])
}

# damage of constraints with strategies
fresults$dicdiff_with <- fresults$dic_constrained_withstrategies - fresults$dic_unconstrained_withstrategies
# damage of constraints without strategies
fresults$dicdiff_without <- fresults$dic_constrained_withoutstrategies - fresults$dic_unconstrained_withoutstrategies
# degree to which damage of constraints is less when strategies are present
fresults$dicdiff_diff <- fresults$dicdiff_with - fresults$dicdiff_without 

write.csv(fresults, file='graphs/model_recovery_cus.csv')
```

## Posterior Predictive Checks Table

```{r posterior_predictive_checks}
source('jags/jags_subtasks-2.r')
source('jags/posterior-predictive-checks.r')

# prepare data file to be consistent with simulated datasets
Data <- ribs[,c('user_id', 'subtask', 'block', 'rt')]
names(Data) <- c('subject', 'subtask_text', 'trial', 'y')
Data$subtask <-  as.numeric(factor(Data$subtask_text, levels=c('informationgathering', 'filtering', 'timetableuse')))
Data$subject <- as.numeric(factor(Data$subject))

predictive_checks <- list()

# unconstrained without strategies
# 1. get posterior samples
# have a good burnin: 3000
# have many iterations: 10000 
# have thinning: 10
posterior_predictive_check_cus <- function(strategies=FALSE, constraints=FALSE, ...) {
    jags_model <- jags_subtasks_gamma(f='power3', strategy_predictors=strategies, theta2_constraint=constraints, 
                                      gamma_constraint=constraints)
    pc_model <- run_jags(jags_model$script, jagsdata,  jags_model$parameters, dic.run=FALSE, showplots=FALSE)
    pc_samples <- do.call(rbind, pc_model$samples)

    # 2. simulate from posterior
    simulate_unconstrained_withoutstrateties <- function(thetas) {
        simulate_data_subtasks_cus(as.list(thetas), constraints=constraints, strategies=strategies)$d
    }
    
    simulations <- simulate_many(pc_samples, simulate_unconstrained_withoutstrateties)
    
    # 3. calculate statistics on simulated data and data
    x <- calculate_statistics(simulations, Data)
    summaryx <- summarise_statistics(x)
    list(summary_statistics=summaryx, raw_statistics=x)
}


settings <- list(n.chains= 1,  n.adapt= 200, burnin = 2000, n.iter= 10000, thin=1)
predictive_checks$unconstrained_withoutstrategies <- posterior_predictive_check_cus(strategies=FALSE, constraints=FALSE)
predictive_checks$constrained_withoutstrategies <- posterior_predictive_check_cus(strategies=FALSE, constraints=TRUE)
predictive_checks$unconstrained_withstrategies <- posterior_predictive_check_cus(strategies=TRUE, constraints=FALSE)
predictive_checks$constrained_withstrategies <- posterior_predictive_check_cus(strategies=TRUE, constraints=TRUE)

lapply(predictive_checks, function(X) X$summary_statistics)

# create the summary table for posterior predictive checks 
extract_checks <- function(statistics_summary, statistics, digits=2) {
    combine_formatted <- function(x, digits) {
        formatted <- specify_decimal(x, digits)
        paste0(formatted['mean'], '\n', '(', formatted['low95'], ' - ', 
               formatted['high95'], ')',
               '\n', 'p=', formatted['pvalue'])
    }
    
    statistics_summary <- statistics_summary[,statistics]
    sapply(colnames(statistics_summary), 
           function(X) combine_formatted(statistics_summary[, X], digits))
}

predictive_checks_table <- sapply(predictive_checks, function(X) 
    extract_checks(X$summary_statistics, colnames(X$summary_statistics))
    )

dataset1 <- specify_decimal(predictive_checks[[1]]$summary_statistics['dataset', ], 2)
predictive_checks_table <- cbind(dataset1,  predictive_checks_table)
            
write.csv(predictive_checks_table, 'graphs/predictive_checks_table.csv')

sink('graphs/predictive_checks_table.csv', append=TRUE)
date()
settings
sink()

temp <- predictive_checks$constrained_withstrategies
```

```{r assorted_output}
# changes this for dataset
sink('graphs/predictive-check-output.txt')
cat('Average p-value on posterior predictive checks')
pcp <- sapply(lapply(predictive_checks, function(X) X$summary_statistics), function(X) X['pvalue', ])
pcp_mean <- apply(pcp, 2, mean)
pcp_f <- cbind(toupper(names(pcp_mean)),  round(pcp_mean, 2))
paste(pcp_f[,1], pcp_f[,2], sep='=', collapse=', ')
cat('\n\n')

cat('Log of productive of p-values on posterior predictive checks')
pcp_log <- apply(pcp, 2, function(X) sum(log(X)))
pcp_log <- cbind(toupper(names(pcp_log)),  round(pcp_log, 2))
paste(pcp_log[,1], pcp_log[,2], sep='=', collapse=', ')
cat('\n\n')

# cat('Time-series Standard error\n')
# timeseries_se <- unlist(sapply(model_fits, function(X) X$statistics[, 'Time-series SE']))
# cat('Median:', median(round(timeseries_se, 5)), '\n')
# cat('Max:', max(round(timeseries_se, 5)))


sink()

```

# Subtask plot
```{r subtask_plots}
source('jags/jags_subtasks-2.r')
jagsdata <- get_data_subtasks()
returnfits_subtasks <- function(strategies=TRUE, constraints=TRUE) {
    jags_object <- run_jags(jags_subtasks_gamma(f='power3', strategy_predictors=strategies, yhat=TRUE,
                                                theta2_constraint=constraints, gamma_constraint=constraints, )$script,
                            jagsdata, 'yhat', dic.run=FALSE, showplots=FALSE, )
    fits_samples <- do.call(rbind, jags_object$samples)
    fits_samples <- fits_samples[,  grep('yhat', colnames(fits_samples), value=TRUE)]
    fits_means <- apply(fits_samples, 2, mean)
    list(fits_means=fits_means, jagsdata=jagsdata)
}
    
subtask_fits <- list() 

# i.e., sfcf means [S]trategy = [F]alse; [C]onstraints = [F]alse
subtask_fits$sfcf <- returnfits_subtasks(strategies=FALSE, constraints=FALSE)
subtask_fits$sfct <- returnfits_subtasks(strategies=FALSE, constraints=TRUE)
subtask_fits$stcf <- returnfits_subtasks(strategies=TRUE, constraints=FALSE)
subtask_fits$stct <- returnfits_subtasks(strategies=TRUE, constraints=TRUE)

# reassemble the dataframe
yhatdata <- data.frame(subject=jagsdata$subject, trial=jagsdata$trial, 
                       yhat_sfcf= subtask_fits$sfcf$fits_means, 
                       yhat_sfct= subtask_fits$sfct$fits_means, 
                       yhat_stcf= subtask_fits$stcf$fits_means, 
                       yhat_stct= subtask_fits$stct$fits_means, 
                       y=jagsdata$y,
                       subtask_index=jagsdata$subtask_index)

yhat_group <- aggregate(yhatdata[, c('y', 'yhat_sfcf', 'yhat_sfct', 'yhat_stcf', 'yhat_stct')], 
                        list(trial=yhatdata$trial, subtask_index=yhatdata$subtask_index), mean)
yhat_group <- merge(yhat_group, meta.subtaskplot, by.x='subtask_index', by.y='subtask_order')
dim(yhat_group)

pdf('graphs/subtaskbyblock-group.pdf')
p <- ggplot(yhat_group, aes(x=trial, y=y), group=subtask) 
p <-p + geom_point(aes(shape=subtask, colour=subtask))
p
tail(yhat_group)

yhat_group$subtask
yhat_group$subtask
dev.off()

# individual level plots
extract_model_yhat <- function(yhat_var='yhat_sfcf') {
    x <- yhatdata[,c("subject", "trial", "y", "subtask_index", yhat_var)]
    names(x)[names(x) == yhat_var] <- 'yhat'
    x$model <- yhat_var
    x
}

yhatdata_split <- lapply(grep('yhat', names(yhatdata), value=TRUE), extract_model_yhat)
yhatdata_long <- do.call(rbind, yhatdata_split)
yhatdata_long$subtask_order <- yhatdata_long$subtask_index
yhatdata_long<- merge(yhatdata_long, meta.subtaskplot) # add meta data
head(yhatdata_long)

# Good cases
# 2 is inconsistent and strategies
# 6 is fairly consistent
# 8 is an example of inconsistent
# 

ids <- c(9, 10, 13, 16)
# ids <- c(2,6,8, 21)
yhatdata_long$strategy <- ifelse(yhatdata_long$model %in% c("yhat_stcf", "yhat_stct"), 
                                 'Strategies', 'No strategies')
yhatdata_long$constraints <- ifelse(yhatdata_long$model %in% c("yhat_stct", "yhat_sfct"), 
                                 'Constrained', 'Unconstrained')
       dput(unique(yhatdata_long$model))
       p <- ggplot(yhatdata_long[yhatdata_long$subject %in% ids, ], aes(trial, y, group=subtask)) + 
    geom_point(aes(colour = subtask, shape=subtask))
p <- p + geom_line(aes(x=trial, y=yhat, linetype=subtask))
p <- p + facet_grid(subject ~ strategy+constraints) + scale_y_continuous("Task completion time (sec)", limits=c(0, 25)) + 
    scale_x_continuous("Block", breaks=c(1,5, 10, 15))
p

pdf('graphs/subtaskfits-individual-examples.pdf')
p
dev.off()
# add lines
```
